name = "acquisition-worker"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
account_id = "c2a379b245edf0bfdd2042b8e3687a95"

[[routes]]
pattern = "converterwebptojpg.com/*"
zone_id = "f654f682837663ce0ec632d66a3ebdc0"

[[routes]]
pattern = "www.converterwebptojpg.com/*"
zone_id = "f654f682837663ce0ec632d66a3ebdc0" 